[package]
name = "postchain-client"
version = "0.0.1"
edition = "2021"

[dependencies]
serde_json = "1.0.48"
reqwest = { version = "0.12.5", features = ["json"] } 
url = "2.5.2"
tokio = { version = "1", features = ["full"] }
asn1 = {version = "0.17.0", features = ["std"] }
secp256k1 = { version = "0.29.0", features = ["rand", "serde"] }
rand = "0.8.5"
hex = "0.4.3"
num-bigint = "0.4.6"