services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ARGS: --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8
      POSTGRES_DB: postchain
      POSTGRES_USER: postchain
      POSTGRES_PASSWORD: postchain
    ports:
      - 5432:5432
  blockchain:
    image: "registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:0.22.2"
    command: chr node start --wipe
    ports:
      - 7740:7740
    depends_on:
      - postgres
    volumes:
      - ./:/usr/app
    environment:
      CHR_DB_URL: jdbc:postgresql://postgres/postchain